# Generated by Django 4.0.3 on 2022-03-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_animal_name_animal_name_female_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Do we work with this animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
    ]
